//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BXIEmpresas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPI_EMPRESAS_dato
    {
        public int iddato { get; set; }
        public string dato { get; set; }
        public string texto1 { get; set; }
        public Nullable<int> valor1 { get; set; }
        public Nullable<int> decimal1 { get; set; }
        public Nullable<int> status { get; set; }
    }
}
