//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BXIEmpresas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPI_EMPRESAS_MOD_registro
    {
        public int idregistro { get; set; }
        public string ruc { get; set; }
        public string razon_social { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string ip { get; set; }
        public Nullable<int> version { get; set; }
        public string moneda_cargo { get; set; }
        public string cuenta_cargo { get; set; }
        public string entidad { get; set; }
        public Nullable<int> firmantes { get; set; }
        public Nullable<System.DateTime> f_registro { get; set; }
        public Nullable<int> status { get; set; }
        public string codoficina { get; set; }
        public Nullable<int> token_fisico { get; set; }
        public Nullable<int> token_digital { get; set; }
        public string usuario_administrador { get; set; }
        public string dni_administrador { get; set; }
        public string nombre_administrador { get; set; }
        public string email_administrador { get; set; }
        public string telefono_administrador { get; set; }
        public string token { get; set; }
    }
}
