//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.BXIEmpresas.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPI_EMPRESAS_representante> BPI_EMPRESAS_representante { get; set; }
        public virtual DbSet<BPI_EMPRESAS_dato> BPI_EMPRESAS_dato { get; set; }
        public virtual DbSet<BPI_EMPRESAS_token> BPI_EMPRESAS_token { get; set; }
        public virtual DbSet<BPI_EMPRESAS_autorizados> BPI_EMPRESAS_autorizados { get; set; }
        public virtual DbSet<BPI_EMPRESAS_MOD_representante> BPI_EMPRESAS_MOD_representante { get; set; }
        public virtual DbSet<BPI_EMPRESAS_MOD_autorizados> BPI_EMPRESAS_MOD_autorizados { get; set; }
        public virtual DbSet<BPI_EMPRESAS_MOD_token> BPI_EMPRESAS_MOD_token { get; set; }
        public virtual DbSet<BPI_EMPRESAS_registro> BPI_EMPRESAS_registro { get; set; }
        public virtual DbSet<BPI_EMPRESAS_MOD_registro> BPI_EMPRESAS_MOD_registro { get; set; }
    
        public virtual ObjectResult<SP_BPI_EMPRESAS_OFICINAS_Result> SP_BPI_EMPRESAS_OFICINAS(string rEGION)
        {
            var rEGIONParameter = rEGION != null ?
                new ObjectParameter("REGION", rEGION) :
                new ObjectParameter("REGION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BPI_EMPRESAS_OFICINAS_Result>("SP_BPI_EMPRESAS_OFICINAS", rEGIONParameter);
        }
    }
}
